In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold

# Load the dataset
df = pd.read_csv('phishing_url_features.csv')

In [19]:

pd.set_option('display.max_columns', None)
df

,url,URLLength,Domain,DomainLength,TLD,TLDLength,NoOfSubDomain,LetterRatioInURL,DigitRatioInURL,NoOfSpecialCharsInURL,PathLength,IsHTTPS,label
0,https://blockchaoin.info/#/,27,blockchaoin,11,info,4,0,0.740741,0.000000,7,1,1,1
1,https://www.insects.org/ced4/crush_freaks.html,46,insects,7,org,3,0,0.782609,0.021739,9,23,1,0
2,https://www.elpasotimes.com/story/opinion/edit...,118,elpasotimes,11,com,3,0,0.703390,0.135593,19,91,1,0
3,http://direct-certs.bankofamerica.com.techdbas...,147,techdbaseurl46,14,cn,2,3,0.482993,0.428571,13,22,0,1
4,https://gotham-magazine.com/lalique-unveils-ep...,53,gotham-magazine,15,com,3,0,0.830189,0.000000,9,26,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
514589,https://www.affiliaxe.com/blog/tag/our-team,43,affiliaxe,9,com,3,0,0.790698,0.000000,9,18,1,0
514590,http://www.thisisdisplay.org/collection/page/p108,49,thisisdisplay,13,org,3,0,0.775510,0.061224,8,21,0,0
514591,http://paypal.com-cgi.arabmakemoney.com/5885d8...,68,arabmakemoney,13,com,3,2,0.661765,0.161765,12,19,0,1
514592,http://www.aspavadiamond.com/themes/ok/ipad,43,aspavadiamond,13,com,3,0,0.813953,0.000000,8,15,0,1
514593,https://www.toplist.cz/stat/605780,34,toplist,7,cz,2,0,0.617647,0.176471,7,12,1,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514594 entries, 0 to 514593
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   url                    514594 non-null  object
 1   URLLength              514594 non-null  int64
 2   Domain                 514581 non-null  object
 3   DomainLength           514594 non-null  int64
 4   TLD                    514594 non-null  object
 5   TLDLength              514594 non-null  int64
 6   NoOfSubDomain          514594 non-null  int64
 7   LetterRatioInURL       514594 non-null  float64
 8   DigitRatioInURL        514594 non-null  float64
 9   NoOfSpecialCharsInURL  514594 non-null  int64
 10  PathLength             514594 non-null  int64
 11  IsHTTPS                514594 non-null  int64
 12  label                  514594 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 51.0+ MB

**DATA SPLITTING**

In [28]:
from sklearn.model_selection import train_test_split, StratifiedKFold


X = df.drop(columns=['label'])
y = df['label']

def get_dist(series):
    return (series.value_counts(normalize=True).sort_index() * 100).round(2).to_dict()

print(f"Original Distribution: {get_dist(y)}\n")

# 2. Random Train-Test Split (80-20)
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X, y, test_size=0.2, random_state=42, stratify=None)

print("--- Random Split Distributions ---")
print(f"Train: {get_dist(y_train_r)}")
print(f"Test:  {get_dist(y_test_r)}\n")

# 3. Stratified Train-Test Split (80-20)
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("--- Stratified Split Distributions ---")
print(f"Train: {get_dist(y_train_s)}")
print(f"Test:  {get_dist(y_test_s)}\n")

# 4. 5-Fold Stratified K-Fold Cross-Validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("--- Stratified 5-Fold CV Distributions ---")
for i, (train_index, val_index) in enumerate(skf.split(X, y), 1):
    y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[val_index]
    print(f"Fold {i} - Train: {get_dist(y_train_fold)} | Val: {get_dist(y_val_fold)}")

Original Distribution: {0: 55.44, 1: 44.56}

--- Random Split Distributions ---
Train: {0: 55.5, 1: 44.5}
Test:  {0: 55.21, 1: 44.79}

--- Stratified Split Distributions ---
Train: {0: 55.44, 1: 44.56}
Test:  {0: 55.44, 1: 44.56}

--- Stratified 5-Fold CV Distributions ---
Fold 1 - Train: {0: 55.44, 1: 44.56} | Val: {0: 55.44, 1: 44.56}
Fold 2 - Train: {0: 55.44, 1: 44.56} | Val: {0: 55.44, 1: 44.56}
Fold 3 - Train: {0: 55.44, 1: 44.56} | Val: {0: 55.44, 1: 44.56}
Fold 4 - Train: {0: 55.44, 1: 44.56} | Val: {0: 55.44, 1: 44.56}
Fold 5 - Train: {0: 55.44, 1: 44.56} | Val: {0: 55.44, 1: 44.56}

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

# Display the shapes of the resulting datasets
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")


# Quick check on the distribution of 'outcome' in the training set
print(f"\nStratified Train Distribution (%):\n{(y_train.value_counts(normalize=True) * 100).round(2)}")

X_train shape: (411675, 12)
X_test shape: (102919, 12)
y_train shape: (411675,)
y_test shape: (102919,)

Stratified Train Distribution (%):
label
0    55.44
1    44.56
Name: proportion, dtype: float64

In [33]:
import numpy as np

num_cols = X_train.select_dtypes(include=['number']).columns

skewness_train = X_train[num_cols].skew()

skewed_features = skewness_train[
    (skewness_train > 0.5) | (skewness_train < -0.5)
].index

print("skewed features:")
print(skewed_features)

skewed features:
Index(['URLLength', 'DomainLength', 'TLDLength', 'NoOfSubDomain',
       'LetterRatioInURL', 'DigitRatioInURL', 'NoOfSpecialCharsInURL',
       'PathLength'],
      dtype='object')

In [34]:
X_train_log = X_train.copy()
X_test_log = X_test.copy()

for col in skewed_features:
    
    if (X_train_log[col] < 0).any():
        
        shift = abs(X_train_log[col].min()) + 1
        
        X_train_log[col] = np.log1p(X_train_log[col] + shift)
        X_test_log[col] = np.log1p(X_test_log[col] + shift)
    
    else:
        
        X_train_log[col] = np.log1p(X_train_log[col])
        X_test_log[col] = np.log1p(X_test_log[col])

**SCALING**

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = X_train_log.select_dtypes(include=['number']).columns

X_train_scaled = X_train_log.copy()
X_test_scaled = X_test_log.copy()

X_train_scaled[num_cols] = scaler.fit_transform(X_train_log[num_cols])
    
X_test_scaled[num_cols] = scaler.transform(X_test_log[num_cols])

**FEATURE SELECTION**

In [39]:
# hanya kolom numerik
X_features = X_train_log.select_dtypes(include=['number'])

print(X_features.columns)

Index(['URLLength', 'DomainLength', 'TLDLength', 'NoOfSubDomain',
       'LetterRatioInURL', 'DigitRatioInURL', 'NoOfSpecialCharsInURL',
       'PathLength', 'IsHTTPS'],
      dtype='object')

In [40]:
spearman_corr_table = X_features.corr(method='spearman')

print("=== Spearman Feature Correlation ===")
display(spearman_corr_table)

=== Spearman Feature Correlation ===

,URLLength,DomainLength,TLDLength,NoOfSubDomain,LetterRatioInURL,DigitRatioInURL,NoOfSpecialCharsInURL,PathLength,IsHTTPS
URLLength,1.000000,0.141939,0.024027,0.158187,-0.108389,0.387838,0.886602,0.716186,-0.012306
DomainLength,0.141939,1.000000,0.065131,-0.139768,0.182549,-0.028505,0.013663,0.054900,-0.071959
TLDLength,0.024027,0.065131,1.000000,-0.085535,0.070983,-0.072272,0.031984,0.014501,0.013579
NoOfSubDomain,0.158187,-0.139768,-0.085535,1.000000,-0.164966,0.212810,0.098897,-0.181805,-0.324789
LetterRatioInURL,-0.108389,0.182549,0.070983,-0.164966,1.000000,-0.867299,-0.179621,0.051836,0.187362
DigitRatioInURL,0.387838,-0.028505,-0.072272,0.212810,-0.867299,1.000000,0.316339,0.169108,-0.164420
NoOfSpecialCharsInURL,0.886602,0.013663,0.031984,0.098897,-0.179621,0.316339,1.000000,0.645950,0.031474
PathLength,0.716186,0.054900,0.014501,-0.181805,0.051836,0.169108,0.645950,1.000000,0.116458
IsHTTPS,-0.012306,-0.071959,0.013579,-0.324789,0.187362,-0.164420,0.031474,0.116458,1.000000

In [41]:
pearson_corr_table = X_features.corr(method='pearson')

print("=== Pearson Feature Correlation ===")
display(pearson_corr_table)

=== Pearson Feature Correlation ===

,URLLength,DomainLength,TLDLength,NoOfSubDomain,LetterRatioInURL,DigitRatioInURL,NoOfSpecialCharsInURL,PathLength,IsHTTPS
URLLength,1.000000,0.154329,0.046050,0.247776,-0.182865,0.396971,0.874704,0.638729,-0.029694
DomainLength,0.154329,1.000000,0.017323,-0.088828,0.111329,0.001413,0.022711,0.050794,-0.071300
TLDLength,0.046050,0.017323,1.000000,-0.061834,0.049344,-0.043324,0.058007,0.029603,-0.013925
NoOfSubDomain,0.247776,-0.088828,-0.061834,1.000000,-0.177643,0.248843,0.171230,-0.150402,-0.299490
LetterRatioInURL,-0.182865,0.111329,0.049344,-0.177643,1.000000,-0.928842,-0.186232,0.005930,0.194661
DigitRatioInURL,0.396971,0.001413,-0.043324,0.248843,-0.928842,1.000000,0.245754,0.148692,-0.205058
NoOfSpecialCharsInURL,0.874704,0.022711,0.058007,0.171230,-0.186232,0.245754,1.000000,0.561077,0.022632
PathLength,0.638729,0.050794,0.029603,-0.150402,0.005930,0.148692,0.561077,1.000000,0.123204
IsHTTPS,-0.029694,-0.071300,-0.013925,-0.299490,0.194661,-0.205058,0.022632,0.123204,1.000000

In [42]:
import numpy as np
import pandas as pd

threshold = 0.8

corr_matrix = X_features.corr(method="spearman")

high_corr = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        
        corr_value = corr_matrix.iloc[i, j]
        
        if abs(corr_value) >= threshold:
            
            high_corr.append({
                "feature_1": corr_matrix.columns[i],
                "feature_2": corr_matrix.columns[j],
                "correlation": corr_value
            })

high_corr_df = pd.DataFrame(high_corr).sort_values(
    by="correlation",
    key=abs,
    ascending=False
)

print("Highly correlated features:")
display(high_corr_df)

Highly correlated features:

               feature_1         feature_2  correlation
1  NoOfSpecialCharsInURL         URLLength     0.886602
0        DigitRatioInURL  LetterRatioInURL    -0.867299